// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/athletes": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Lists the authenticated coach's athletes, newest first. Defaults to private athletes only — the coach's ongoing working list — since public athletes are one-off plan-link deliveries; pass athlete_type to widen that. Paginated: meta carries the total, limit and offset.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "athletes"
                ],
                "summary": "List athletes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Case-insensitive partial match on first or last name",
                        "name": "q",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "private",
                            "public",
                            "all"
                        ],
                        "type": "string",
                        "description": "Which athletes to include; defaults to private",
                        "name": "athlete_type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Page size, 1-100",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Rows to skip",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_athlete.athleteResponse"
                                            }
                                        },
                                        "meta": {
                                            "$ref": "#/definitions/internal_athlete.listMeta"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Adds an athlete to the authenticated coach's roster. The owning coach comes from the bearer token — a coach_id in the body is ignored. Omitting athlete_type creates a private athlete.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "athletes"
                ],
                "summary": "Create an athlete",
                "parameters": [
                    {
                        "description": "Athlete details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_athlete.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_athlete.athleteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/login": {
            "post": {
                "description": "Verifies phone + password and returns a signed JWT. The error is the same whether the phone or the password was wrong.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Log in a coach",
                "parameters": [
                    {
                        "description": "Login credentials",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_coach.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_coach.loginResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/auth/signup": {
            "post": {
                "description": "Creates a coach account. v1 is single-coach, so this is open with no admin gate.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Sign up a coach",
                "parameters": [
                    {
                        "description": "Signup details",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_coach.signupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_coach.coachResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "429": {
                        "description": "Too Many Requests",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/api/v1/coaches/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns the profile of the coach identified by the bearer token.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get the authenticated coach",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.SuccessEnvelope"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/internal_coach.coachResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "description": "Reports whether the service and its database connection are healthy.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_server.healthzOKResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/internal_server.healthzErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Code is one of the Code* constants; clients branch on it, unlike Message.",
                    "type": "string",
                    "example": "validation_failed"
                },
                "fields": {
                    "description": "Fields is set for request-validation failures only.",
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "Message is human-readable and may change freely.",
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorEnvelope": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "$ref": "#/definitions/github_com_AbolfazlTayyar_gogym_internal_httpx.ErrorBody"
                },
                "success": {
                    "type": "boolean",
                    "example": false
                }
            }
        },
        "github_com_AbolfazlTayyar_gogym_internal_httpx.SuccessEnvelope": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {},
                "meta": {},
                "success": {
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "internal_athlete.athleteResponse": {
            "type": "object",
            "properties": {
                "athlete_type": {
                    "type": "string",
                    "example": "private"
                },
                "created_at": {
                    "type": "string",
                    "example": "2026-09-24T09:30:00Z"
                },
                "experience_level": {
                    "type": "string",
                    "example": "beginner"
                },
                "first_name": {
                    "type": "string",
                    "example": "Sara"
                },
                "goal": {
                    "type": "string",
                    "example": "lose 5kg"
                },
                "height": {
                    "type": "number",
                    "example": 172
                },
                "id": {
                    "type": "string",
                    "example": "3f0b1c6e-2a1d-4f7b-9c3e-6d5a4b3c2d1e"
                },
                "injuries": {
                    "type": "string",
                    "example": "left shoulder impingement"
                },
                "last_name": {
                    "type": "string",
                    "example": "Ahmadi"
                },
                "phone": {
                    "type": "string",
                    "example": "09372144430"
                },
                "updated_at": {
                    "type": "string",
                    "example": "2026-09-24T09:30:00Z"
                }
            }
        },
        "internal_athlete.createRequest": {
            "type": "object",
            "properties": {
                "athlete_type": {
                    "type": "string",
                    "example": "private"
                },
                "experience_level": {
                    "type": "string",
                    "example": "beginner"
                },
                "first_name": {
                    "type": "string",
                    "example": "Sara"
                },
                "goal": {
                    "type": "string",
                    "example": "lose 5kg"
                },
                "height": {
                    "type": "number",
                    "example": 172
                },
                "injuries": {
                    "type": "string",
                    "example": "left shoulder impingement"
                },
                "last_name": {
                    "type": "string",
                    "example": "Ahmadi"
                },
                "phone": {
                    "type": "string",
                    "example": "09372144430"
                }
            }
        },
        "internal_athlete.listMeta": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer",
                    "example": 20
                },
                "offset": {
                    "type": "integer",
                    "example": 0
                },
                "total": {
                    "type": "integer",
                    "example": 42
                }
            }
        },
        "internal_coach.coachResponse": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string",
                    "example": "Ada"
                },
                "id": {
                    "type": "string",
                    "example": "b8f1c9de-8f0a-4c1e-9a2b-2f6b6b8e2b3a"
                },
                "last_name": {
                    "type": "string",
                    "example": "Lovelace"
                },
                "phone": {
                    "type": "string",
                    "example": "09372144430"
                }
            }
        },
        "internal_coach.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "phone"
            ],
            "properties": {
                "password": {
                    "type": "string",
                    "example": "correct-horse-battery-staple"
                },
                "phone": {
                    "type": "string",
                    "example": "09372144430"
                }
            }
        },
        "internal_coach.loginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "internal_coach.signupRequest": {
            "type": "object",
            "required": [
                "first_name",
                "last_name",
                "password",
                "phone"
            ],
            "properties": {
                "first_name": {
                    "type": "string",
                    "example": "Ada"
                },
                "last_name": {
                    "type": "string",
                    "example": "Lovelace"
                },
                "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "correct-horse-battery-staple"
                },
                "phone": {
                    "type": "string",
                    "example": "09372144430"
                }
            }
        },
        "internal_server.healthzErrorResponse": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "example": "failed to connect to database"
                },
                "status": {
                    "type": "string",
                    "example": "unavailable"
                }
            }
        },
        "internal_server.healthzOKResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Type \"Bearer\" followed by a space and a JWT token.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GoGym API",
	Description:      "API for the GoGym coaching platform.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
