DROP TABLE IF EXISTS block_movement;
DROP TABLE IF EXISTS block;
DROP TABLE IF EXISTS day;
DROP TABLE IF EXISTS plan;
DROP TABLE IF EXISTS athlete_measurement;
DROP TABLE IF EXISTS athlete;
DROP TABLE IF EXISTS movement;
DROP TABLE IF EXISTS coach;
